pipeline {
    // 没有 agent 指令的话, 声明式流水线不仅无效, 它也不可能完成任何工作
    agent any
        // 使用全局定义工具
        tools {
            maven 'maven'
            jdk 'java-1.8-openjdk'
        }


        stages {
        stage('init') {
                           steps {
                            script{
                              def dockerPath = tool 'docker' //全局配置里的docker
                              env.PATH = "${dockerPath}/bin:${env.PATH}" //添加了系统环境变量上
                            }
                           }
                    }
            stage('build') {
                steps {
                    echo 'Building..'
                    // 输出路径
                    sh 'pwd'
                    sh 'mvn --version'
                    sh 'java -version'
                    sh 'docker ps'
                    sh 'docker ps -a'
                    sh 'docker images'
                    sh 'mvn -B -DskipTests clean package docker:build'
 
                }
            }

            stage('build222') {
                steps {
                    echo 'Building..'
                    // 输出路径
                    sh 'cd /var/lib/jenkins/workspace/ && ll'


                }
            }

        }
}